### ISSUE TITLE
仕様？バグ？と要望

### ISSUE THREAD

**Issue by pick2** [r7kamura/amazon_url_shortner#3]
GoogleChrome 49.0.2623.87 を使用していますが
新しいタブを開いた時にURLが補正されません。
そのようなときにも補正されるようにして欲しいです。

あと、以下のような携帯のページのアマゾンURLも補正するように対応して欲しいです。
http://www.amazon.co.jp/gp/aw/d/B00ECROGMA/ref=me_amb_97167169_2/376-8743572-4074603?aid=aw_srgw&apid=97167169&arc=1201&arid=03Q8N6YM6KWAKZRW8B7G&asn=center-7&m=A35I8LZM6OTLVS

**Comment by r7kamura** [comment]
報告ありがとうございます。そして長らく放置してしまい申し訳ありません。いろいろあり、Chromeウェブストアから登録情報不足ということで掲載を取り下げられたこともあって、対応が遅くなってしまいました。

> 新しいタブを開いた時にURLが補正されません。

というのが自分の理解と異なっていたら後で教えてほしいですが、新しいタブで商品ページを開いた際にも、動作しているようでした。また、現在では少なくともそのパターンのURLでも動作しているようですので、Closeしようと考えています。

ちなみに、私はWindowsのGoogle Chrome 86.0.4240.111で確認しました。バージョン情報も丁寧に書いていただきありがとうございます。あれからもう37もバージョンが上がってしまいましたね。

不具合報告とご要望、ありがとうございました。
